---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waitlist-django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: waitlist-django-app
  template:
    metadata:
      labels:
        app: waitlist-django-app
    spec:
      containers:
        - name: waitlist-django-container
          image: richardsrobinr/waitlist-django-app:latest
          ports:
            - containerPort: 8000
