apiVersion: apps/v1
kind: Deployment
metadata:
  name: waitlist-django-app
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: waitlist-django-app
  template:
    metadata:
      labels:
        app: waitlist-django-app
    spec:
      containers:
      - name: waitlist-django-container
        image: richardsrobinr/waitlist-django-app:latest  # Your Docker image
        ports:
          - containerPort: 8000  # Django default port
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
