---
apiVersion: v1
kind: Service
metadata:
  name: waitlist-django-service
spec:
  type: NodePort
  selector:
    app: waitlist-django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
