apiVersion: v1
kind: Service
metadata:
  name: waitlist-django-service
spec:
  type: LoadBalancer
  selector:
    app: waitlist-django-app  # Match the labels in the Deployment
  ports:
  - protocol: TCP
    port: 80  # External port
    targetPort: 8000  # Port inside the container
