# Generated by Django 4.2.11 on 2024-04-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlecontacts', '0002_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
